steps:
  # STEP 1: Build JAR
  - name: maven:3.9.6-eclipse-temurin-17
    entrypoint: mvn
    args: ["clean", "package", "-DskipTests"]
    dir: backend/nexthome-app

  # STEP 2: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/dogood-488720/nexthome-backend/nexthome-app:latest
      - backend/nexthome-app

  # STEP 3: Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/dogood-488720/nexthome-backend/nexthome-app:latest

  # STEP 4: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy nexthome-app \
          --image us-central1-docker.pkg.dev/dogood-488720/nexthome-backend/nexthome-app:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --set-env-vars "SERVER_PORT=8080,DB_URL=jdbc:mysql://nexthome-nexthome.l.aivencloud.com:14556/vacancy_db,CORS_ALLOWED_ORIGINS=https://nexthome-live.github.io,DB_USERNAME=avnadmin,DB_PASSWORD=AVNS_gnhYrsECOIB0hcmdylj"

options:
  logging: CLOUD_LOGGING_ONLY
